//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibilioteca_prestamos_EVWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int id_prestamo { get; set; }
        public Nullable<System.DateTime> FechaPres { get; set; }
        public Nullable<System.DateTime> FechaDev { get; set; }
        public Nullable<int> id_Libro { get; set; }
        public Nullable<int> id_Usuario { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
